Maja is a Vala to Javascript compiler <http://lethalman.hostei.com/maja/>
Maja can produce standard javascript, without dova or browser-specific code.

In order to run the javascript code generated by Maja, maja-utils.js hasto
be loaded first. It contains common code for all Maja projects.

This package also offers:
 - js-lang.vapi: standard browser API for javascript
 - dova-base-0.1.js: compatibility layer for the Dova profile
 - dova-js.vala: Dova profile specific code enhancing Web programming,
   whose generated code is runnable both in Vala and Maja
